### PR TITLE
Retry on upload failure

### LINKED ISSUE #3026: [CLI] Retry strategy for upload failures
Image

the current (of the upcoming ant client) behavior of just erroring out on every error of a batched upload does make it pretty useless to really go for large uploads.

i personally would prefer a "just retry with same settings 1 minute later" flag
then we may try to go for uploads for some hours every minute while gas prices are high ... but who cares ...
(ideally retrying the chunk with failed chunk-proof wouldn't happen isolated but simply with the next (shortened by the failed chunks) batch of chunks) ... from what i observe it usually works on next upload attempt ... but i'm sure that's more difficult so just "keep pushing" would be cooler than the current retrying in my terminal and seeing it always start from the beginnning :D)

### PR DESCRIPTION
**Pull request by maqi**
### Description

This work is on top of PR https://github.com/maidsafe/autonomi/pull/3036 to carry out auto retry on upload failure.
Which avoids forcing user to carry out re-uploads manually and have to go through the encryption and quoting uploaded chunks again and again.

Newly added command line opt:
* `retry-failed` :  default to be 0 indicating not carry out retry on upload failure. 
                          set to be the times of total content chunks.
                          Will carry out round-robin style (push the failed chunks to the tail of the upload task queue as scheduled for retry) upto the max threshold (X times total content chunks).

Example usage: `--retry-failed 3`

Thanks for the @rid-dim , here is a screenshot (with detailed chunk/file info blurred) of a upload run against the production net.
Showing the retry works and as an example of the output
image

### Related Issue

Fixes https://github.com/maidsafe/autonomi/issues/3026 .

### Type of Change

Please mark the types of changes made in this pull request.

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

File: autonomi/src/client/high_level/files/fs_shared.rs [hunk 1]
```diff
@@ -66,7 +69,6 @@ impl Client {
     }
 
     /// Processes file uploads with payment in batches
-    /// Returns total cost of uploads or error if any upload fails
     pub(crate) async fn pay_and_upload(
```
Comment (grumbach) [inline autonomi/src/client/high_level/files/fs_shared.rs]: Is that not the case anymore?

File: autonomi/src/client/high_level/files/fs_shared.rs [hunk 2]
```diff
@@ -99,15 +101,48 @@ impl Client {
...
+            let candidate_chunks = aggregated_chunks.len();
+
+            let batch_result = self
+                .process_chunk_batch(
+                    &mut aggregated_chunks,
+                    &mut receipts,
+                    &mut free_chunks_counts,
+                    payment_option.clone(),
+                    retry_on_failure,
+                )
```
Comment (grumbach) [inline autonomi/src/client/high_level/files/fs_shared.rs]: Not introduced in this PR but significantly more affected with it: is there any way we can remove all these "mut"? They make it hard to know what's going on.

**Review by grumbach — COMMENTED** [review]
The upload code might need some refactoring as it is getting more and more complex.

File: autonomi/src/client/high_level/files/fs_shared.rs (hunk 1 above)
Comment (maqi) [reply autonomi/src/client/high_level/files/fs_shared.rs]: oh, I think that's removed by the community member, which was using infinite loop to retry

will add some more comments in make it clearer

**Review by grumbach — APPROVED** [review]
LGTM
