### PR TITLE
Fix upload symlink 3258

### LINKED ISSUE #3258: files::dir_content_upload() - fails when uploading a directory which is a symlink
When `dir_content_upload()` is asked to encrypt a directory which is a symbolic link to the actual directory, an error occurs in `autonomi::self_encryption::stream_encryption
pub(crate) async fn encrypt_directory_files()`.

This appears to be because the following code ([here](https://github.com/maidsafe/autonomi/blob/main/autonomi/src/self_encryption/stream_encryption.rs#L274-L276)) does not skip the symlink, and so tries to encrypt it:
```
        if entry.file_type().is_dir() {
            continue;
        }
```

**Reproduce the Bug**
On a Linux system using...
```
$ ant --version
Autonomi Client v0.4.9
Network version: ant/1.0/1
Package version: 2025.10.1.6
Git info: stable / 647513f / 2025-10-15
```
Create a symlink to a directory and upload it:
```
rm -rf test && mkdir test && echo abc > test/test.txt && ln -s test test-link
ant --local file upload test-link
Logging to directory: "/home/mrh/.local/share/autonomi/client/logs/log_2025-10-16_17-34-50"
Connecting to a local Autonomi network...
Connected to the network
🎯 Using single node payment mode (default - saves gas fees)
Uploading data to network...
Encrypting file: "test-link"..
Encrypting file: "test-link/test.txt"..
Error during file encryption: Could not read file "test-link": Os { code: 21, kind: IsADirectory, message: "Is a directory" }

   0: Failed to upload file
   1: Encryption error

Location:
   ant-cli/src/commands/file.rs:135
```

I expect this can be fixed by changing the above code to:
```
        if !entry.file_type().is_file() {
            continue;
        }
```

I will test the fix and submit a PR.

### PR DESCRIPTION
**Pull request by happybeing**
### Description

Skip encryption of symbolic links (as well as directories) when uploading.

### Related Issue

Fixes #3258 

### Type of Change

Please mark the types of changes made in this pull request.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please describe):

### Checklist

Please ensure all of the following tasks have been completed:

- [ ] I have read the [contributing guidelines](CONTRIBUTING.md).
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have updated the documentation accordingly.
- [ ] I have followed the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) guidelines for commit messages.
- [ ] I have verified my commit messages with [commitlint](https://commitlint.js.org/#/).

### CODE REVIEW

File: autonomi/src/self_encryption/stream_encryption.rs [hunk 1]
```diff
@@ -271,7 +271,8 @@ pub(crate) async fn encrypt_directory_files(
     for entry in walkdir::WalkDir::new(&dir_path) {
         let entry = entry?;
 
-        if entry.file_type().is_dir() {
+        // Skip files and symbolic links
```
Comment (maqi) [inline autonomi/src/self_encryption/stream_encryption.rs]: the comment may shall be :  `Skip non-files, i.e. directories or symbolic links`  ?

**Comment by maqi** [comment]
Hi, @happybeing ,

Thank you very much for the work.
Nice catch !

I am happy to got it merged in once the comment got updated.

Cheers,

File: autonomi/src/self_encryption/stream_encryption.rs (hunk 1 above)
Comment (happybeing) [reply autonomi/src/self_encryption/stream_encryption.rs]: Oops! It should be "Skip directories and symbolic links". Sorry, will push an update!

**Review by maqi — APPROVED** [review]
